### ISSUE TITLE
Question - Extracting nested values

### ISSUE THREAD

**Issue by CTOUT** [yokawasa/logstash-output-azure_loganalytics#15]
Hi,

In the CSV output module, you can extract nested entries by typing something like '[geoip][country_name]'.  When attempting this same approach with the azure_loganalytics module it does not output any data.

Is there a different way of achieving this in this module?

**Comment by yokawasa** [comment]
@CTOUT 
Instead of extracting nested fields directly in the azure_loganalytics module which doesn't support,  you can add [mutate filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate) steps by which you can catch the existing nested fields and add them as new fields. Please see this discussion:
- https://discuss.elastic.co/t/filter-mutate-add-field-from-nested-field/170231

let me know how it work for you

**Comment by CTOUT** [comment]
Hi @yokawasa - thanks for the info.
We have since attempted this but although the mutate configuration seems to work fine in an offline logstash implementation, it does not seem to work when applied to ELK.  Likely a legacy configuration issue more than anything, hence why we were hoping we could do it via your addon itself.

Thanks again!
